name: balenaCloud production releases

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  raspberry-pi-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguel3/hello-node 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
  raspberry-pi-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguel3/hello-node-pi1 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
