name: balenaCloud releases

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  raspberry-pi-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 20k-ultra/balena-ci@remove-github-token-input 
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguel3/hello-node 
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
  raspberry-pi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 20k-ultra/balena-ci@remove-github-token-input 
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguel3/hello-node 
          versionbot: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
