name: balenaCloud

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [hello-node]
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/balena-io/deploy-to-balena-action:v0.10.0
        name: 'Deploy to miguel/${{ matrix.fleet }}'
        id: build
        with:
          balena_token: ${{ secrets.BALENA_STAGING_TOKEN }} 
          environment: balena-staging.com
          fleet: 'miguel/${{ matrix.fleet }}' 
      - name: Log release ID built
        run: echo "Built release ID - ${{ steps.build.outputs.release_id }}"
      - name: Log release version built
        run: echo "Built release version - ${{ steps.build.outputs.version}}"
