name: balenaCloud

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [hello-node]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@master 
        name: 'Deploy to miguel3/${{ matrix.fleet }}'
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }} 
          environment: balena-cloud.com
          fleet: 'miguel/${{ matrix.fleet }}' 
          cache: false
          versionbot: true
      - name: Log release ID built
        run: echo "Built release ID - ${{ steps.build.outputs.release_id }}"
      - name: Log release version built
        run: echo "Built release version - ${{ steps.build.outputs.version}}"
