name: balenaCloud

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [hello-node, hello-node-pi1]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@24-terminate-build
        name: 'Deploy to miguel/${{ matrix.fleet }}'
        with:
          balena_token: ${{ secrets.BALENA_STAGING_TOKEN }} 
          environment: balena-staging.com
          fleet: 'miguel/${{ matrix.fleet }}' 
