name: balenaCloud

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [hello-node, hello-node-pi1]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@add-target-default-branch
        name: 'Deploy to miguel/${{ matrix.fleet }}'
        with:
          balena_token: ${{ secrets.BALENA_STAGING_TOKEN }} 
          environment: balena-staging.com
          fleet: 'miguel/${{ matrix.fleet }}' 
          create_tag: true
