name: balenaCloud
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fleet: [hello-node, hello-node-pi1]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@ab77-patch-1
        name: "Deploy to miguel/${{ matrix.fleet }}"
        with:
          balena_token: ${{ secrets.BALENA_STAGING_TOKEN }}
          environment: balena-staging.com
          fleet: "miguel/${{ matrix.fleet }}"
          create_tag: true
          default_branch: "master"
