name: workflow-name

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  job1:
    name: job-name
    runs-on: [ubuntu-latest]
    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME
      - name: Dump event
        run: cat "$GITHUB_EVENT_PATH"
      - name: Dump ENV
        run: env
