name: balenaci # Workflow must contain a name

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: balena-io/balena-ci
          token: ${{ secrets.PERSONAL_TOKEN }} # stored in GitHub secrets 
          path: .github/actions/balena-ci
      - name: Run My Action
        uses: ./.github/actions/balena-ci
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguels-org/octobalena
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
