on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    name: deploy release
    steps:
      - name: Deploy release
        id: deploy
        uses: 20k-ultra/deploy-release@v2