name: "balenaCloud"
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    name: "Deploy release"
    steps:
        id: deploy
        uses: 20k-ultra/deploy-release@v5