name: testing

on:
  push:

jobs:
  job1:
    runs-on: [ubuntu-latest]
    name: Log who I am
    steps:
      - name: Dump ENV
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: cat "$GITHUB_EVENT_PATH"
