name: balenaci # Workflow must contain a name

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: miguel3/hello-node 
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
