name: "balenaCloud"

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: balena-io-playground/github-actions/actions/find-release@master
        id: found
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_name: build release # name of the check suite with build
      - run: echo "Found release ID ${{ steps.found.outputs.release_id }}"